# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-10-15 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slate',
            name='mode',
            field=models.CharField(choices=[('main', 'Main'), ('showdown', 'Showdown')], default='main', max_length=20),
        ),
    ]
