# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-10-20 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_slate_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slate',
            name='mode',
            field=models.CharField(choices=[('classic', 'Classic'), ('showdown', 'Showdown')], default='classic', max_length=20),
        ),
    ]
